name: Dev Deployment

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Dev
      env:
        API_KEY: ${{ secrets.DEV_API_KEY }}
      run: |
        echo "Deploying to Dev..."
        # 实际部署命令