name: Prod Deployment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirm PROD deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Prod
      env:
        API_KEY: ${{ secrets.PROD_API_KEY }}
      run: |
        echo "Deploying to Prod..."
        # 实际部署命令