name: Stage Deployment

on:
  workflow_dispatch:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Stage
      env:
        API_KEY: ${{ secrets.STAGE_API_KEY }}
      run: |
        echo "Deploying to Stage..."
        # 实际部署命令